services:
  api:
    image: mansaron/ecommerce-api:latest
    container_name: ecommerce-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      start-period: 60s
      retries: 3
