spring:
  data:
    mongodb:
      username: ${DB_USER}
      database: ${DB_DATABASE}
      password: ${DB_PASSWORD}
      uri: ${DB_URI}
  config:
    import: file:env.properties
  application:
    name: ecommerce backend
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

logging.level.root: info
logging.level.co.za.ecommerce: DEBUG
logging.level.org.springframework.web: DEBUG

aws:
  s3:
    access-key: ${ACCESS}
    secret-key: ${SECRET}
    bucket-name: ${BUCKET_NAME}
    region: ${REGION}