spring.application.name=ecommerce backend
spring.config.import=file:env.properties
spring.data.mongodb.uri=${DB_URI}
spring.data.mongodb.database=${DB_DATABASE}
spring.data.mongodb.username=${DB_USER}
spring.data.mongodb.password=${DB_PASSWORD}

app.jwt-secret=${JWT}

logging.level.root: info
logging.level.co.za.ecommerce: DEBUG
logging.level.org.springframework.web: DEBUG

aws.s3.bucket-name:${BUCKET_NAME}
aws.s3.region:${REGION}
aws.s3.access-key:${ACCESS}
aws.s3.secret-key:${SECRET}